sudo: false
language: node_js
node_js:
  - 6
  - 8
  - 10
matrix:
  fast_finish: true
script: npm run travis
notifications:
  email: false
after_success:
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
