sudo: false
language: node_js
node_js:
  - 6
  - 8
matrix:
  fast_finish: true
before_script:
  - npm prune
script: npm run travis
notifications:
  email: false
after_success:
  - npm run semantic-release
